version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dannita2628!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Dannita2628!", "-Q", "select 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  cliente-persona:
    build: ../microservice-cliente-persona
    container_name: cliente-persona
    ports:
      - "8081:8081"
    depends_on:
      - sqlserver
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: dev

  cuenta-movimientos:
    build: ../microservice-cuenta-movimientos
    container_name: cuenta-movimientos
    ports:
      - "8082:8082"
    depends_on:
      - sqlserver
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: dev
